- sudo:
    - shell:
        - command: ./bat/install
          description: Installing "bat"
          stdout: true

- link:
    ~/.config/bat/config:
      path: bat/config.conf
      create: true
      force: true
