- sudo:
    - shell:
        - command: ./sharkdp/install bat
          description: Installing "bat"
          stdout: true

- link:
    ~/.config/bat/config:
      path: sharkdp/bat.conf
      create: true
      force: true
