- sudo:
    - shell:
        - command: dpkg -i ./exa/exa_0.9.0_amd64.deb
          description: Installing "exa"
          stdout: true

- link:
    ~/.config/zsh/exa.zsh:
      path: exa/aliases.zsh
      create: true
