- sudo:
    - shell:
        - command: ./exa/install
          description: Installing "exa"
          stdout: true

- link:
    ~/.config/zsh/exa.zsh:
      path: exa/aliases.zsh
      create: true
