- shell:
    - command: ./trysudo apt install -y gdb
      description: Installing "gdb"
      stdin: true
      stdout: true

- link:
    ~/.gdbinit.d: gdb/gdbinit.d
    ~/.gdbinit: gdb/gdbinit