- shell:
    - command: ./trysudo apt install -y gdb
      description: Installing "gdb"
      stdin: true
      stdout: true

- create:
    - ~/.gdbinit.d

- link:
    ~/.gdbinit.d/dashboard: gdb/gdbinit.d/dashboard
    ~/.gdbinit.d/init: gdb/gdbinit.d/init
    ~/.gdbinit.d/useful: gdb/gdbinit.d/useful
    ~/.gdbinit: gdb/gdbinit