- sudo:
    - apt: gdb

- create:
    - ~/.gdbinit.d

- link:
    ~/.gdbinit.d/dashboard: gdb/gdbinit.d/dashboard
    ~/.gdbinit.d/init: gdb/gdbinit.d/init
    ~/.gdbinit.d/useful: gdb/gdbinit.d/useful
    ~/.gdbinit: gdb/gdbinit
