- defaults:
    download:
      quiet: true
      executable: true

- sudo:
    - apt:
        - rlwrap
        - ncat
        - p7zip-full

    - shell:
        - command: pip3 install -U -q pwntools
          description: Installing "pwntools"
          stdin: true
          stdout: true

        - command: ./gobuster/install
          description: Installing "gobuster"
          stdout: true

        - command: ./scripts/install-wordlists
          description: Installing "wordlists"
          stdout: true

    - create:
        - /usr/share/enum
        - /usr/share/webshells/php

    - download:
        /usr/share/enum/linuxprivchecker.py:
          url: https://raw.githubusercontent.com/sleventyeleven/linuxprivchecker/master/linuxprivchecker.py
          description: linuxprivchecker
        /usr/share/enum/linuxprivchecker3.py:
          url: https://raw.githubusercontent.com/cervoise/linuxprivcheck/master/linuxprivchecker3.py
          description: linuxprivchecker3
        /usr/share/webshells/php/p0wny-shell.php:
          url: https://raw.githubusercontent.com/flozz/p0wny-shell/master/shell.php
          description: p0wny-shell

- link:
    ~/.config/zsh/kali.zsh:
      path: zsh/kali.zsh
      create: true
