- sudo:
    - apt:
        - rlwrap
        - ncat
        - p7zip-full

    - shell:
        - command: pip3 install -U -q pwntools
          description: Installing "pwntools"
          stdin: true
          stdout: true

        - command: ./gobuster/install
          description: Installing "gobuster"
          stdout: true

- link:
    ~/.config/zsh/kali.zsh:
      path: zsh/kali.zsh
      create: true
