- clean:
    ~/:
    ~/.config:
      recursive: true

- sudo:
    - shell:
        - command: apt update -qq
          description: Updating apt sources
          stdout: true
          stderr: true

    - apt:
        - progress
        - unzip
        - python3-pip

    - shell:
        - command: pip3 install -U -q downloader-cli
          description: Installing "downloader-cli"
          stdin: true
          stdout: true


- link:
    ~/.local/bin/dotbot:
      path: install
      create: true
