- clean:
    ~/:
    ~/.config:
      recursive: true

- shell:
    - command: ./trysudo apt update -qq
      description: Updating apt sources
      stdin: true
      stdout: true

    - command: ./trysudo apt install -y progress unzip python3-pip
      description: Installing "progress" "unzip" "python3-pip"
      stdin: true
      stdout: true

- link:
    ~/.local/bin/dotbot:
      path: install
      create: true
