- link:
    ~/.config/zsh/wsl.zsh:
      path: zsh/wsl.zsh
      create: true

- sudo:
    - shell:
        - command: ./sharkdp/install hyperfine
          description: Installing "hyperfine"
          stdout: true

        - command: ./sharkdp/install hexyl
          description: Installing "hexyl"
          stdout: true

        - command: ./sharkdp/install fd
          description: Installing "fd"
          stdout: true
