- defaults:
    git:
      shallow: true
    link:
      create: true

- git:
    ~/.oh-my-zsh:
      url: https://github.com/ohmyzsh/ohmyzsh
      description: Oh My Zsh
      method: clone

- git:
    ~/.oh-my-zsh/custom/plugins/fast-syntax-highlighting: 
      url: https://github.com/zdharma/fast-syntax-highlighting
      description: "Oh My Zsh (fast-syntax-highlighting)"
    ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions: 
      url: https://github.com/zsh-users/zsh-autosuggestions
      description: "Oh My Zsh (zsh-autosuggestions)"
    ~/.oh-my-zsh/custom/plugins/zsh-z: 
      url: https://github.com/agkozak/zsh-z
      description: "Oh My Zsh (zsh-z)"
    ~/.oh-my-zsh/custom/themes/powerlevel10k: 
      url: https://github.com/romkatv/powerlevel10k
      description: "Oh My Zsh (powerlevel10k)"

- link:
    ~/.zshrc:
      path: zsh/zshrc
      force: true
    ~/.config/zsh/common.zsh:
      path: zsh/common.zsh
    ~/.config/p10k/rainbow.zsh:
      path: p10k/rainbow.zsh
    ~/.config/p10k/robbyrussell.zsh:
      path: p10k/robbyrussell.zsh

- sudo:
    - apt: zsh

- shell:
    - command: 'zsh --version'
      stdout: true

    - command: ./zsh/changeshell
      description: "Making zsh the default shell"
      stdin: true
      stderr: true
      stdout: true
