FROM python:bullseye

LABEL org.opencontainers.image.source=https://github.com/jcwillox/dotfiles

ENV TERM xterm-256color
ENV DOTBOT_NO_UPDATE_REPO 1
ENV CI true

RUN apt update && apt install -y sudo zsh

RUN sh -c "$(curl -fsSL https://github.com/jcwillox/dotbot/raw/main/scripts/install/dotbot.sh)"

RUN mkdir -p /root/.local/state/dotbot \
    && echo "{\"directory\": \"/root/dotfiles\"}" > /root/.local/state/dotbot/state.json

COPY . /root/dotfiles

RUN dotbot

WORKDIR /root

CMD "zsh"
