FROM ubuntu:focal

RUN apt update && DEBIAN_FRONTEND="noninteractive" \
    apt install -y sudo python3 python3-pip unzip curl git zsh tzdata

COPY . /root/dotfiles

ENV TERM xterm-256color

RUN /root/dotfiles/install -U wsl

WORKDIR /root

CMD "zsh"
