#!/usr/bin/env bash

if [ ! "$(which gh)" ]; then
    current_version=0.0.0
    echo "gh: not installed"
else
    current_version=$(gh --version | grep -oP 'version \K[0-9.]+')
    echo "gh: found $current_version"
fi

latest_version=$(curl -s https://github.com/cli/cli/releases/latest | grep -oE '[0-9]+.[0-9\.]+')

if [[ "$current_version" == "$latest_version" ]]; then
    echo "gh: up-to-date"
else
    echo "gh: new version found $latest_version"
    echo "gh: downloading..."

    curl -fsSLo gh_amd64.deb "https://github.com/cli/cli/releases/download/v$latest_version/gh_${latest_version}_linux_amd64.deb"
    sudo dpkg -i gh_amd64.deb
    rm gh_amd64.deb

    # update completions
    sudo sh -c "gh completion -s zsh > /usr/local/share/zsh/site-functions/_gh && echo 'gh: updated completions'"
fi
