#!/usr/bin/env bash

if [ ! "$(which exa)" ]; then
    current_version=0.0.0
    echo "exa: not installed"
else
    current_version=$(exa --version | grep -oE "[0-9\.]+")
    echo "exa: found $current_version"
fi

latest_version=$(curl -s https://github.com/ogham/exa/releases/latest | grep -oE '[0-9]+.[0-9\.]+')

if [[ "$current_version" == "$latest_version" ]]; then
    echo "exa: up-to-date"
else
    echo "exa: new version found $latest_version"
    echo "exa: downloading..."

    curl -fsSLo exa.zip "https://github.com/ogham/exa/releases/download/v$latest_version/exa-linux-x86_64-${latest_version}.zip"
    unzip exa.zip

    sudo mv exa-linux-x86_64 /usr/local/bin/exa
    echo "exa: installed /usr/local/bin/exa"

    rm exa.zip
fi

