#!/usr/bin/env bash

if [ ! "$(which exa)" ]; then
    current_version=0.0.0
    echo "exa: not installed"
else
    current_version=$(exa --version | grep -oE "v[0-9\.]+")
    echo "exa: found $current_version"
fi

latest_version=$(curl -s https://github.com/ogham/exa/releases/latest | grep -oE 'v[0-9]+.[0-9\.]+')

if [[ "$current_version" == "$latest_version" ]]; then
    echo "exa: up-to-date"
else
    echo "exa: new version found $latest_version"
    echo "exa: downloading..."

    curl -fsSLo exa.zip "https://github.com/ogham/exa/releases/download/$latest_version/exa-linux-x86_64-${latest_version}.zip"

    sudo unzip -q exa.zip -d exa-zip
    sudo mv exa-zip/bin/exa /usr/local/bin
    sudo mv exa-zip/completions/exa.zsh /usr/local/share/zsh/site-functions/_exa
    sudo mv exa-zip/completions/exa.bash /etc/bash_completion.d/exa
    sudo mkdir -p /usr/local/share/man/man1 /usr/local/share/man/man5
    sudo mv exa-zip/man/exa.1 /usr/local/share/man/man1
    sudo mv exa-zip/man/exa_colors.5 /usr/local/share/man/man5

    echo "exa: installed /usr/local/bin/exa"

    rm exa.zip
    sudo rm -rf exa-zip
fi
