#!/usr/bin/env bash

if [ "$(which exa)" ]; then
    current_version=$(exa --version | grep -oE "[0-9\.]+")
    echo "exa: removing $current_version"

    ROOT_FILE="/usr/local/bin/exa"
    sudo rm "$ROOT_FILE" && echo "exa: removed $ROOT_FILE"
fi
