#!/usr/bin/env bash

if [ "$(which gobuster)" ]; then
    echo "gobuster: removing"

    FILE="$HOME/.local/bin/gobuster"
    if [ -f "$FILE" ]; then
        rm "$FILE" && echo "gobuster: removed ~/.local/bin/gobuster"
    fi

    ROOT_FILE="/usr/local/bin/gobuster"
    if [ "$(groups | grep "sudo\|root")" ]; then 
        sudo rm "$ROOT_FILE" && echo "gobuster: removed $ROOT_FILE"
    fi
fi
