#!/usr/bin/env bash

USER=${SUDO_USER:-$USER}

current_shell=$(getent passwd $USER | cut -d : -f 7)
zsh_path=$(which zsh)

if [ "$current_shell" ] && [ "$current_shell" != "$zsh_path" ]; then
    chsh -s $zsh_path $USER
fi
