#!/usr/bin/env zsh
export ZSH="$HOME/.oh-my-zsh"

plugins=(
  git
  fast-syntax-highlighting
  zsh-autosuggestions
  z
  docker-compose
  pip
  sudo
  dirhistory
  dirpersist
  httpie
  urltools
  encode64
  vscode
  python
  isodate
  copybuffer
  copypath
  copyfile
  command-not-found
  history-substring-search
  nvm
  fnm
  aliases
  extract
  nmap
  bun
  uv
  catimg
  1password
  gh
)

if (( $+commands[go] )); then
  plugins+=("golang")
fi

if (( $+commands[apt] )); then
  plugins+=("ubuntu")
fi

if (( $+commands[nmap] )); then
  plugins+=("nmap")
fi

if [ -f ~/.config/zsh/kali.zsh ]; then
  plugins+=("web-search")
fi

if [[ "$OSTYPE" == darwin* ]]; then
  plugins=("brew" "${plugins[@]}")
  plugins+=("web-search" "macos")
fi

for file in ~/.config/zsh/*; do
  source "$file"
done

if [ "$TERM_PROGRAM" != "vscode" ] &&
   [ "$TERM_PROGRAM" != "Jetbrains.Fleet" ] &&
   [ "$TERMINAL_EMULATOR" != "JetBrains-JediTerm" ]; then
  cd - > /dev/null
fi

export PNPM_HOME="$HOME/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

if [[ -f ~/.config/tabtab/zsh/__tabtab.zsh ]]; then
  source ~/.config/tabtab/zsh/__tabtab.zsh
fi
