#!/usr/bin/env zsh
export ZSH="$HOME/.oh-my-zsh"

plugins=(
  git
  fast-syntax-highlighting
  zsh-autosuggestions
  zsh-z
  docker-compose
  pip
  sudo
  dirhistory
  dirpersist
  httpie
  urltools
  encode64
  vscode
  python
  isodate
  copybuffer
  copydir
  copyfile
  command-not-found
  history-substring-search
)

if (( $+commands[go] )); then
  plugins+=("golang")
fi

if (( $+commands[apt] )); then
  plugins+=("ubuntu")
fi

if [ -f ~/.config/zsh/kali.zsh ]; then
  plugins+=("web-search")
fi

for file in ~/.config/zsh/*; do
  source "$file"
done

cd - > /dev/null
